app = "wc-ducomb"
primary_region = "ord"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  API_PORT = "5001"
  IBM_HOST = "10.0.0.7"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 2
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"